export const PROTEZ_ROUTE = '/protezPage'
export const TEAM_ROUTE = '/teamPage'
export const ABOUTUS_ROUTE = '/aboutUsPage'
export const MAIN_ROUTE = '/'
export const SERVICES_ROUTE = '/servicesPage'
export const LOGIN_ROUTE = '/login'